leads = [
    {"name": "Alice Johnson", "email": "alice@techcorp.com", "score": 95, "gdpr_ok": True, "employees": 1200},
    {"name": "Bob Smith", "email": "bob@startup.io", "score": 78, "gdpr_ok": True, "employees": 25},
    {"name": "Carol Davis", "email": "carol@bigbank.com", "score": 88, "gdpr_ok": True, "employees": 5000},
    {"name": "David Brown", "email": "david@gmail.com", "score": 65, "gdpr_ok": False, "employees": 1},
    {"name": "Emma Wilson", "email": "emma@cloudlabs.ai", "score": 92, "gdpr_ok": True, "employees": 350},
    {"name": "Frank Moore", "email": "frank@yahoo.com", "score": 45, "gdpr_ok": False, "employees": 1},
    {"name": "Grace Taylor", "email": "grace@retailgroup.co.uk", "score": 83, "gdpr_ok": True, "employees": 800},
    {"name": "Henry Anderson", "email": "henry@healthtech.io", "score": 98, "gdpr_ok": True, "employees": 220},
    {"name": "Isabella Thomas", "email": "isabella@marketpro.com", "score": 71, "gdpr_ok": True, "employees": 55},
    {"name": "Jack Jackson", "email": "jack@hotmail.com", "score": 39, "gdpr_ok": False, "employees": 1},

    {"name": "Katie White", "email": "katie@finserve.com", "score": 87, "gdpr_ok": True, "employees": 750},
    {"name": "Liam Harris", "email": "liam@salesflow.ai", "score": 90, "gdpr_ok": True, "employees": 110},
    {"name": "Mia Martin", "email": "mia@insightlabs.io", "score": 81, "gdpr_ok": True, "employees": 45},
    {"name": "Noah Thompson", "email": "noah@enterprisegroup.com", "score": 97, "gdpr_ok": True, "employees": 3000},
    {"name": "Olivia Garcia", "email": "olivia@gmail.com", "score": 52, "gdpr_ok": False, "employees": 1},
    {"name": "Paul Martinez", "email": "paul@buildsmart.co", "score": 77, "gdpr_ok": True, "employees": 150},
    {"name": "Quinn Robinson", "email": "quinn@aiforge.ai", "score": 91, "gdpr_ok": True, "employees": 600},
    {"name": "Ryan Clark", "email": "ryan@consultplus.com", "score": 68, "gdpr_ok": True, "employees": 40},
    {"name": "Sophia Rodriguez", "email": "sophia@globalbank.com", "score": 94, "gdpr_ok": True, "employees": 8000},
    {"name": "Thomas Lewis", "email": "thomas@yahoo.com", "score": 44, "gdpr_ok": False, "employees": 1},

    {"name": "Uma Lee", "email": "uma@innovatech.com", "score": 85, "gdpr_ok": True, "employees": 420},
    {"name": "Victor Walker", "email": "victor@nextwave.io", "score": 73, "gdpr_ok": True, "employees": 70},
    {"name": "Will Hall", "email": "will@megacorp.com", "score": 99, "gdpr_ok": True, "employees": 12000},
    {"name": "Xavier Allen", "email": "xavier@gmail.com", "score": 61, "gdpr_ok": False, "employees": 1},
    {"name": "Yasmin Young", "email": "yasmin@greenenergy.co.uk", "score": 89, "gdpr_ok": True, "employees": 950},
    {"name": "Zach King", "email": "zach@futuredata.ai", "score": 93, "gdpr_ok": True, "employees": 330},
    {"name": "Ava Scott", "email": "ava@retailhub.com", "score": 79, "gdpr_ok": True, "employees": 85},
    {"name": "Benjamin Adams", "email": "ben@securebank.com", "score": 96, "gdpr_ok": True, "employees": 6500},
    {"name": "Chloe Baker", "email": "chloe@startuphub.io", "score": 74, "gdpr_ok": True, "employees": 18},
    {"name": "Daniel Nelson", "email": "daniel@hotmail.com", "score": 50, "gdpr_ok": False, "employees": 1},

    {"name": "Ella Carter", "email": "ella@cloudscale.ai", "score": 88, "gdpr_ok": True, "employees": 275},
    {"name": "Finn Mitchell", "email": "finn@marketleader.com", "score": 84, "gdpr_ok": True, "employees": 720},
    {"name": "Georgia Perez", "email": "georgia@dataworks.io", "score": 82, "gdpr_ok": True, "employees": 65},
    {"name": "Harry Roberts", "email": "harry@manufacturepro.com", "score": 91, "gdpr_ok": True, "employees": 1400},
    {"name": "Ivy Turner", "email": "ivy@gmail.com", "score": 58, "gdpr_ok": False, "employees": 1},
    {"name": "James Phillips", "email": "james@analyticslab.ai", "score": 90, "gdpr_ok": True, "employees": 210},
    {"name": "Keira Campbell", "email": "keira@logisticsgroup.com", "score": 86, "gdpr_ok": True, "employees": 2000},
    {"name": "Leo Parker", "email": "leo@smbtools.io", "score": 69, "gdpr_ok": True, "employees": 22},
    {"name": "Maya Evans", "email": "maya@insureplus.com", "score": 95, "gdpr_ok": True, "employees": 3100},
    {"name": "Nathan Edwards", "email": "nathan@yahoo.com", "score": 47, "gdpr_ok": False, "employees": 1},

    {"name": "Olivia Collins", "email": "olivia@futurebank.com", "score": 92, "gdpr_ok": True, "employees": 4800},
    {"name": "Peter Stewart", "email": "peter@techstack.ai", "score": 87, "gdpr_ok": True, "employees": 160},
    {"name": "Ruby Sanchez", "email": "ruby@growthlabs.io", "score": 83, "gdpr_ok": True, "employees": 95},
    {"name": "Samuel Morris", "email": "samuel@globalretail.com", "score": 97, "gdpr_ok": True, "employees": 10000},
    {"name": "Tara Rogers", "email": "tara@gmail.com", "score": 56, "gdpr_ok": False, "employees": 1},
    {"name": "Umar Reed", "email": "umar@aiplatform.ai", "score": 94, "gdpr_ok": True, "employees": 410},
    {"name": "Violet Cook", "email": "violet@enterprisecloud.com", "score": 89, "gdpr_ok": True, "employees": 2600},
    {"name": "William Morgan", "email": "william@startupgrowth.io", "score": 72, "gdpr_ok": True, "employees": 30},
    {"name": "Xena Bell", "email": "xena@cybersecure.com", "score": 98, "gdpr_ok": True, "employees": 1800},
    {"name": "Yusuf Murphy", "email": "yusuf@hotmail.com", "score": 43, "gdpr_ok": False, "employees": 1}
]